import { join } from "node:path";
import { existsSync, mkdirSync, rmSync, writeFileSync, chmodSync } from "node:fs";
import type { GitHooksConfig, HookType } from "../config/config-model.ts";
import { ALL_HOOK_TYPES } from "../config/config-model.ts";

const HOOKS_DIR = ".git/hooks";

// Installs hook scripts for every hook defined in the config.
// Always cleans all known hooks first to avoid stale scripts.
export function installHooks(config: GitHooksConfig): void {
  const hooksDir = getHooksDir();

  // Remove all previously managed hooks before reinstalling
  for (const hookType of ALL_HOOK_TYPES) {
    removeHookFile(hookType, hooksDir);
  }

  for (const hookType of config.hooks.keys()) {
    writeHookFile(hookType, hooksDir);
  }
}

// Removes only the hook scripts that are currently in the config
export function uninstallHooks(config: GitHooksConfig): void {
  const hooksDir = getHooksDir();

  for (const hookType of config.hooks.keys()) {
    removeHookFile(hookType, hooksDir);
  }
}

function writeHookFile(hookType: HookType, hooksDir: string): void {
  const hookPath = join(hooksDir, hookType);
  writeFileSync(hookPath, generateScript(hookType), "utf8");
  // Git requires the hook file to be executable
  chmodSync(hookPath, 0o755);
  console.log(`✅ Installed ${hookType}`);
}

function removeHookFile(hookType: HookType, hooksDir: string): void {
  const hookPath = join(hooksDir, hookType);
  if (existsSync(hookPath)) {
    rmSync(hookPath);
    console.log(`🗑️  Removed ${hookType}`);
  }
}

function getHooksDir(): string {
  const hooksDir = join(process.cwd(), HOOKS_DIR);

  if (!existsSync(hooksDir)) {
    throw new Error(
      "No .git/hooks directory found. Are you inside a git repository?"
    );
  }

  return hooksDir;
}

// The generated script tries bunx first, then falls back to npx.
// $1 is passed for commit-msg so the validator can read the message file.
function generateScript(hookType: HookType): string {
  const arg = hookType === "commit-msg" ? ' "$1"' : "";
  return `#!/bin/sh
# Generated by commitguard — do not edit manually

if command -v bunx >/dev/null 2>&1; then
  bunx commitguard run ${hookType}${arg}
elif command -v npx >/dev/null 2>&1; then
  npx commitguard run ${hookType}${arg}
else
  echo "❌ commitguard: neither bunx nor npx found in PATH."
  echo "   Install Bun (https://bun.sh) or Node.js and make sure it is in your PATH."
  exit 1
fi
`;
}
